SET ANSI_NULLS ON
GO
-- When you want manual SQL for your first migration from the initial one...
-- You do it by naming it MsSql-1.sql, (-1) being the sequence number of the migration.
-- By this example this SQL here will be added to the DbDeploy_MsSQL-1.sql generated by MsAddMigration.ps1
GO

