using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EfCore.Boost.Model.Attributes
{
    /// <summary>
    /// Shorthand for Primary key attibute, autogenerated, should be of type int, long or GuId
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class DbAutoUidAttribute : Attribute
    {
    }

    /// <summary>
    /// Marks a Guid property as a database-generated ID whose type and default value
    /// are configured per provider (SqlServer / PostgreSQL / MySQL).
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class DbGuidAttribute : Attribute
    {
    }

    #region strings

    /// <summary>
    /// Short string codes less than StrShort, lets say maxlen 30
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class StrCodeAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand for maxlen string (50)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class StrShortAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand for maxlen string (256)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class StrMedAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand for maxlen string (512)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class StrLongAttribute : Attribute
    {
    }

    /// <summary>
    /// Just for the clarification this is equal to not setting maxlen attribute that translate to longtext, text, nvarchar(max) etc depending on provider
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class TextAttribute : Attribute
    {
    }

    #endregion
    #region decimals

    /// <summary>
    /// Shorthand decimal money precision (19,4)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class MoneyAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand decimal rate precision (18,8)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class RateAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand decimal quantity precision (18,8)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class QtyAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand hig number and precission for decimal (38,19)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class ScientificAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand decimal sorting (38,19)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class SortRankAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand for price (19,4)
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class PriceAttribute : Attribute
    {
    }

    /// <summary>
    /// Shorthand for percentage (18,8)  //needs presission - not just for display - same as rate
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class PercentageAttribute : Attribute
    {
    }

    #endregion
}
