using Microsoft.EntityFrameworkCore;

namespace BoostX.Model;

public partial class BoostXDbContext
{
    /// <summary>
    /// Seeded data is part of the model and will be part of the SQL generated by the migration.
    /// The code below in OnModelCreating is also part of this DLL and the end application.
    /// Therefore, for large datasets, it's recommended to import data post-migration.
    /// The migration project will demonstrate how to do this.
    /// </summary>
    /// <param name="modelBuilder"></param>
    private static void OnModelData(ModelBuilder modelBuilder)
    {
        // For autogenerated id's we use negative values to avoid conflicts with none-seeded data
        DateTimeOffset eD = new(1970, 1, 1, 0, 0, 0, TimeSpan.Zero);
        modelBuilder.Entity<IpInfo>().HasData(
            new IpInfo() { Id = -1, HostName = "Localhost", IpNo = "127.0.0.1", LastChangedUtc = eD, Processed = true }
            );
    }
}

