using Microsoft.EntityFrameworkCore;

namespace BoostX.Model;

public partial class BoostXDbContext
{
    /// <summary>
    /// Configures seed data for the database model.
    /// Seeded data is included in the EF Core migrations.
    /// </summary>
    /// <param name="modelBuilder">The model builder instance.</param>
    private static void OnModelData(ModelBuilder modelBuilder)
    {
        // For autogenerated id's we use negative values to avoid conflicts with none-seeded data
        DateTimeOffset eD = new(1970, 1, 1, 0, 0, 0, TimeSpan.Zero);
        modelBuilder.Entity<IpInfo>().HasData(
            new IpInfo() { Id = -1, HostName = "Localhost", IpNo = "127.0.0.1", LastChangedUtc = eD, Processed = true }
            );
    }
}

