using EfCore.Boost.DbRepo;
using EfCore.Boost.UOW;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using static BoostX.Model.BoostXDbContext;

namespace BoostX.Model;

public class BoostXUow(IConfiguration cfg, string cfgName) : UowFactory<BoostXDbContext>(cfg, cfgName)
{
    #region dbsets

    // We can use EfLongIdRepo<IpInfo> instead of EfRepo<IpInfo> since IpInfo has a long Id-column as an autogenerated primary key.
    public EfLongIdRepo<IpInfo> IpInfos => new(Ctx, DbType);
    public EfReadRepo<IpInfoView> IpInfoViews => new(Ctx, DbType); //Or even EfLongIdReadRepo<IpInfoView>

    #endregion

    #region SP

    // Example stored procedure call, to get ID of matching or inserted row.
    // See the matching Migrate project for the SP/function behind this
    public async Task<long?> GetIpId(string ipNo)
    {
        return await this.RunRoutineLongAsync(BoostXDbContext.DefaultSchemaName, "GetIpId", [new DbParmInfo("@IpNo", ipNo)]);
    }

    // Example of getting a typed record from a Stored Procedure
    // See the matching Migrate project for the SP/function and the view behind this
    // NOTE: This is not exactly a practical implementation, since you can use the view instead directly, but this is here for demonstration purposes
    public async Task<IpInfoView?> GetIpInfoViewByIdAsync(long ipId)
    {
        return await SetUpRoutineQuery<IpInfoView>(BoostXDbContext.DefaultSchemaName, "GetIpViewByIpId", [new DbParmInfo("@IpId", ipId)]).FirstOrDefaultAsync();
    }
    #endregion
}
