// <auto-generated />
using System;
using BoostTest.TestDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoostTest.TestDb.Migrations.PgSQL.MgDbTest
{
    [DbContext(typeof(DbTest))]
    [Migration("20260308130832_InitDbTest")]
    partial class InitDbTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Heading")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("RowID")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastChanged");

                    b.HasIndex("RowID")
                        .IsUnique();

                    b.ToTable("MyTable", "my");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Balance = 350m,
                            Code = "BD",
                            Created = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5730), new TimeSpan(0, 0, 0, 0, 0)),
                            Discount = 5m,
                            Heading = "Baldo",
                            LastChanged = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5729), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            RowID = new Guid("7ea1a206-4cea-4297-bc7e-b1bf15d56b27"),
                            RowVersion = 0L,
                            Status = 1
                        },
                        new
                        {
                            Id = -2L,
                            Balance = 200m,
                            Code = "Mn",
                            Created = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5820), new TimeSpan(0, 0, 0, 0, 0)),
                            Discount = 0m,
                            Heading = "Mando",
                            LastChanged = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5819), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Stefan",
                            RowID = new Guid("b398b742-2e81-4590-86d6-36e3cffe7f5d"),
                            RowVersion = 0L,
                            Status = 2
                        });
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("MyInfo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MyInfo");

                    b.HasIndex("ParentId");

                    b.ToTable("MyTableRef", "my");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Amount = 300m,
                            Created = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5935), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChanged = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5935), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            MyInfo = "BigData",
                            ParentId = -1L,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = -2L,
                            Amount = 50m,
                            Created = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5938), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChanged = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5938), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            MyInfo = "BiggerData",
                            ParentId = -1L,
                            RowVersion = 0L
                        },
                        new
                        {
                            Id = -3L,
                            Amount = 200m,
                            Created = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5939), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChanged = new DateTimeOffset(new DateTime(2026, 3, 8, 13, 8, 31, 753, DateTimeKind.Unspecified).AddTicks(5939), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Stefan",
                            MyInfo = "OtherData",
                            ParentId = -2L,
                            RowVersion = 0L
                        });
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRefView", b =>
                {
                    b.Property<long>("RefId")
                        .HasColumnType("bigint");

                    b.Property<long>("MyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Heading")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MyInfo")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("ParLastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParLastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("RowID")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.HasKey("RefId", "MyId");

                    b.ToTable((string)null);

                    b.ToView("MyTableRefView", "my");
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRef", b =>
                {
                    b.HasOne("BoostTest.TestDb.DbTest+MyTable", "MyTable")
                        .WithMany("MyTableRefs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyTable");
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTable", b =>
                {
                    b.Navigation("MyTableRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
