// <auto-generated />
using System;
using BoostTest.TestDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoostTest.TestDb.Migrations.PgSQL.MgDbTest
{
    [DbContext(typeof(DbTest))]
    partial class DbTestModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("RowID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastChanged");

                    b.HasIndex("RowID")
                        .IsUnique();

                    b.ToTable("MyTable", "my");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            LastChanged = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            RowID = new Guid("ac4b0a74-e0b6-42eb-b11c-71ac0db378be")
                        },
                        new
                        {
                            Id = -2L,
                            LastChanged = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Stefan",
                            RowID = new Guid("caa5a062-c9bb-494f-bf9d-538e64f20b6a")
                        });
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MyInfo")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MyInfo");

                    b.HasIndex("ParentId");

                    b.ToTable("MyTableRef", "my");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            LastChanged = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            MyInfo = "BigData",
                            ParentId = -1L
                        },
                        new
                        {
                            Id = -2L,
                            LastChanged = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Baldr",
                            MyInfo = "BiggerData",
                            ParentId = -1L
                        },
                        new
                        {
                            Id = -3L,
                            LastChanged = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastChangedBy = "Stefan",
                            MyInfo = "OtherData",
                            ParentId = -2L
                        });
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRefView", b =>
                {
                    b.Property<long>("RefId")
                        .HasColumnType("bigint");

                    b.Property<long>("MyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MyInfo")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("RefLastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefLastChangedBy")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("RowID")
                        .HasColumnType("uuid");

                    b.HasKey("RefId", "MyId");

                    b.ToTable((string)null);

                    b.ToView("MyTableRefView", "my");
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTableRef", b =>
                {
                    b.HasOne("BoostTest.TestDb.DbTest+MyTable", "MyTable")
                        .WithMany("MyTableRefs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyTable");
                });

            modelBuilder.Entity("BoostTest.TestDb.DbTest+MyTable", b =>
                {
                    b.Navigation("MyTableRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
