//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoostAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoostAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async database write operations like &apos;{0}&apos; should be awaited.  
        ///Fire-and-forget calls may cause data loss or hide database errors..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &apos;{0}&apos; is not awaited. Await the method to ensure database changes are applied and errors are observed..
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async UOW method must be awaited.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code blocks on an EF Core async query task using Result, Wait(), or GetAwaiter().GetResult() inside an async method. Blocking on Task defeats the benefits of asynchronous EF I/O and can cause thread starvation or deadlocks in ASP.NET applications. Prefer using &apos;await&apos; on the async query method (for example &apos;await query.ToListAsync()&apos;) instead of blocking..
        /// </summary>
        internal static string BlockingEfQueryTaskWaitDescription {
            get {
                return ResourceManager.GetString("BlockingEfQueryTaskWaitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking on EF async query tasks using &apos;{0}&apos; inside an async method can cause deadlocks; use &apos;await&apos; instead.
        /// </summary>
        internal static string BlockingEfQueryTaskWaitMessageFormat {
            get {
                return ResourceManager.GetString("BlockingEfQueryTaskWaitMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid blocking on EF async query tasks.
        /// </summary>
        internal static string BlockingEfQueryTaskWaitTitle {
            get {
                return ResourceManager.GetString("BlockingEfQueryTaskWaitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async database write operations like &apos;{0}&apos; should be awaited.  
        ///Fire-and-forget calls may cause data loss or hide database errors..
        /// </summary>
        internal static string RepoAsyncAwaitDescription {
            get {
                return ResourceManager.GetString("RepoAsyncAwaitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &apos;{0}&apos; is not awaited. Await the method to ensure database operations are applied and errors are observed..
        /// </summary>
        internal static string RepoAsyncAwaitMessageFormat {
            get {
                return ResourceManager.GetString("RepoAsyncAwaitMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async Repo method must be awaited.
        /// </summary>
        internal static string RepoAsyncAwaitTitle {
            get {
                return ResourceManager.GetString("RepoAsyncAwaitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking synchronous repository operations in async code can cause deadlocks and thread starvation. Use async versions instead..
        /// </summary>
        internal static string RepoSyncInAsyncDescription {
            get {
                return ResourceManager.GetString("RepoSyncInAsyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to synchronous repository method &apos;{0}&apos; inside an async method; use the async counterpart instead.
        /// </summary>
        internal static string RepoSyncInAsyncMessageFormat {
            get {
                return ResourceManager.GetString("RepoSyncInAsyncMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid synchronous repository methods in async code.
        /// </summary>
        internal static string RepoSyncInAsyncTitle {
            get {
                return ResourceManager.GetString("RepoSyncInAsyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This call executes a synchronous EF Core query inside an async method, blocking the thread. Use async EF Core query methods such as ToListAsync(), FirstAsync(), SingleAsync(), or CountAsync() to avoid potential deadlocks and improve scalability..
        /// </summary>
        internal static string SyncLinqInAsyncDescription {
            get {
                return ResourceManager.GetString("SyncLinqInAsyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous EF query operator &apos;{0}&apos; in async method — use async counterpart (e.g. &apos;{0}Async&apos;)..
        /// </summary>
        internal static string SyncLinqInAsyncMessageFormat {
            get {
                return ResourceManager.GetString("SyncLinqInAsyncMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async EF Core query methods.
        /// </summary>
        internal static string SyncLinqInAsyncTitle {
            get {
                return ResourceManager.GetString("SyncLinqInAsyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This call executes a synchronous UOW async method within async function.  Use relevand async method instead that does not block the trhead thus avoiding potential deadlocks and improve scalability..
        /// </summary>
        internal static string UowSyncInAsyncDescription {
            get {
                return ResourceManager.GetString("UowSyncInAsyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous UOW method &apos;{0}&apos; in async method — use async counterpart (&apos;{0}Async&apos;).
        /// </summary>
        internal static string UowSyncInAsyncMessageFormat {
            get {
                return ResourceManager.GetString("UowSyncInAsyncMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async UOW method.
        /// </summary>
        internal static string UowSyncInAsyncTitle {
            get {
                return ResourceManager.GetString("UowSyncInAsyncTitle", resourceCulture);
            }
        }
    }
}
