CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'my') THEN
        CREATE SCHEMA my;
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE my."MyTable" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowVersion" bigint NOT NULL,
    "RowID" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Code" varchar(30) NOT NULL,
    "Heading" varchar(256),
    "Balance" numeric(19,4) NOT NULL,
    "Status" integer NOT NULL,
    "Discount" numeric(18,8) NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastChangedBy" varchar(256) NOT NULL,
    CONSTRAINT "PK_MyTable" PRIMARY KEY ("Id")
);

CREATE TABLE my."MyTableRef" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowVersion" bigint NOT NULL,
    "ParentId" bigint NOT NULL,
    "MyInfo" varchar(256) NOT NULL,
    "Amount" numeric(19,4) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "LastChangedBy" varchar(256) NOT NULL,
    CONSTRAINT "PK_MyTableRef" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MyTableRef_MyTable_ParentId" FOREIGN KEY ("ParentId") REFERENCES my."MyTable" ("Id") ON DELETE RESTRICT
);

INSERT INTO my."MyTable" ("Id", "Balance", "Code", "Created", "Discount", "Heading", "LastChanged", "LastChangedBy", "RowID", "RowVersion", "Status")
VALUES (-2, 200.0, 'Mn', TIMESTAMPTZ '2026-03-22T11:38:26.457385+00:00', 0.0, 'Mando', TIMESTAMPTZ '2026-03-22T11:38:26.457385+00:00', 'Stefan', '78c3d2ed-77b8-4669-9afe-8260b25de03f', 0, 2);
INSERT INTO my."MyTable" ("Id", "Balance", "Code", "Created", "Discount", "Heading", "LastChanged", "LastChangedBy", "RowID", "RowVersion", "Status")
VALUES (-1, 350.0, 'BD', TIMESTAMPTZ '2026-03-22T11:38:26.457383+00:00', 5.0, 'Baldo', TIMESTAMPTZ '2026-03-22T11:38:26.457383+00:00', 'Baldr', 'a59ad86d-a231-484d-8d77-a60997ab6ecb', 0, 1);

INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-3, 200.0, TIMESTAMPTZ '2026-03-22T11:38:26.457393+00:00', TIMESTAMPTZ '2026-03-22T11:38:26.457393+00:00', 'Stefan', 'OtherData', -2, 0);
INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-2, 50.0, TIMESTAMPTZ '2026-03-22T11:38:26.457393+00:00', TIMESTAMPTZ '2026-03-22T11:38:26.457393+00:00', 'Baldr', 'BiggerData', -1, 0);
INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-1, 300.0, TIMESTAMPTZ '2026-03-22T11:38:26.457392+00:00', TIMESTAMPTZ '2026-03-22T11:38:26.457392+00:00', 'Baldr', 'BigData', -1, 0);

CREATE INDEX "IX_MyTable_LastChanged" ON my."MyTable" ("LastChanged");

CREATE UNIQUE INDEX "IX_MyTable_RowID" ON my."MyTable" ("RowID");

CREATE INDEX "IX_MyTableRef_MyInfo" ON my."MyTableRef" ("MyInfo");

CREATE INDEX "IX_MyTableRef_ParentId" ON my."MyTableRef" ("ParentId");

SELECT setval(
    pg_get_serial_sequence('my."MyTable"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTable") + 1,
        nextval(pg_get_serial_sequence('my."MyTable"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('my."MyTableRef"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTableRef") + 1,
        nextval(pg_get_serial_sequence('my."MyTableRef"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322113826_InitDbTest', '8.0.24');

COMMIT;

