<#
.SYNOPSIS
EFCore.Boost helper that adds the next EF Core migration for the PostgreSQL DbContext.
Go to the PS folder in terminal and run the script, e.g. .\PgAddMigration.ps1

.DESCRIPTION
This script adds a new migration on top of the existing PostgreSQL migration chain.

Unlike the initial migration script, this does not clean/remove the current provider migrations.
It enables the selected provider migration files by renaming .xcs files back to .cs, while disabling
the other provider folders by renaming their active .cs files to .xcs.

The migration name is generated by taking the next migration number from the provider folder and
appending it to the default add-migration name, for example: AddBoostCTX-2.

The final deploy SQL file is versioned, for example:
Migrations\DbDeploy_Postgres-2.pgsql

The extra hand-written SQL file is also versioned, for example:
SQL\Postgres-2.pgsql
#>

param(
    [string]$ProjectDir,
    [string]$ConnName = "BoostXPg",
    [string]$SqlOutFileName
)

# If no ProjectDir passed, infer from script location:
# script lives in /PS under the project folder
if (-not $ProjectDir) {
    $ProjectDir = Split-Path $PSScriptRoot -Parent
}

$ErrorActionPreference = "Stop"

Write-Host "=== EF Postgres: Adding next migration for PostgreSQL ==="

# Build paths relative to project dir
$Project = Join-Path $ProjectDir "BoostX.Migrate.csproj"

Write-Host "PSScriptRoot: $PSScriptRoot"
Write-Host "ProjectDir:   $ProjectDir"
Write-Host "Project name: $Project"
Write-Host "ConnName:     $ConnName"
Write-Host ""

# Import helpers relative to this script
$helperPath = Join-Path $PSScriptRoot "helpers.ps1"
. $helperPath

# Make sure we have Postgres as current provider without deleting existing migrations
Set-MigrationProviderForAdd -ProjectDir $ProjectDir -Provider "Postgres"

$providerInfo = Get-MigrationProviderInfo -ProjectDir $ProjectDir -Provider "Postgres"
if ($providerInfo.MigrationCount -eq 0 -or [string]::IsNullOrWhiteSpace($providerInfo.LastMigrationName)) {
    throw "No existing Postgres migration was found. Use PgMigrate.ps1 to create the initial migration before using PgAddMigration.ps1."
}
$nextMigrationNumber = $providerInfo.NextNumber
$fromMigration = $providerInfo.LastMigrationName

if (-not $SqlOutFileName) {
    $SqlOutFileName = "Migrations\DbDeploy_Postgres-$nextMigrationNumber.pgsql"
}

$migrations = @(
    @{ Name = "AddBoostCTX-$nextMigrationNumber"; Context = "BoostCTX"; OutDir = "Migrations/Postgres/SnapBoostCTX"; OutFile = "Migrations/Postgres/AddBoostCTX-$nextMigrationNumber.pgsql" }
)

$filesInOrder = @(
    "Migrations/Postgres/AddBoostCTX-$nextMigrationNumber.pgsql",
    "SQL/Postgres-$nextMigrationNumber.pgsql"
)

Write-Host "Next migration number: $nextMigrationNumber"
Write-Host "Deploy SQL file:       $SqlOutFileName"
Write-Host ""

foreach ($m in $migrations) {
    Write-Host "-> Adding migration $($m.Name) ($($m.Context))"

    dotnet ef migrations add $m.Name `
        --context $m.Context `
        --project $Project `
        --output-dir $m.OutDir `
        -- `
        --connName $ConnName

    if ($LASTEXITCODE -ne 0) {
        throw "dotnet ef migrations add failed for migration $($m.Name) ($($m.Context)) with exit code $LASTEXITCODE"
    }

    $outFile = Join-Path $ProjectDir $m.OutFile

    Write-Host "-> Creating SQL script for added migration $($m.Name) ($($m.Context))"

    dotnet ef migrations script $fromMigration $m.Name `
        --context $m.Context `
        --project $Project `
        --output $outFile `
        -- `
        --connName $ConnName

    if ($LASTEXITCODE -ne 0) {
        throw "dotnet ef migrations script failed for migration $($m.Name) ($($m.Context)) with exit code $LASTEXITCODE"
    }
}

$existingFiles = @()

foreach ($relPath in $filesInOrder) {
    $fullPath = Join-Path $ProjectDir $relPath
    if (Test-Path $fullPath) {
        $existingFiles += $fullPath
    } else {
        Write-Warning "Missing SQL file (skipping): $fullPath"
    }
}

if ($existingFiles.Count -eq 0) {
    throw "No input SQL files found. Nothing to merge."
}

$deployPath = Join-Path $ProjectDir $SqlOutFileName

@"
/*
    Database deploy script (Postgres)
    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
    ConnName: $ConnName
    Added migration: $($migrations[0].Name)
*/
"@ | Set-Content -Path $deployPath -Encoding UTF8

foreach ($file in $existingFiles) {
    $name = [System.IO.Path]::GetFileName($file)
    Write-Host "Appending: $name"

    @(
        ""
        "/*** BEGIN $name ***/"
        ""
    ) | Add-Content -Path $deployPath

    Get-Content $file | Add-Content -Path $deployPath

    @(
        ""
        "/*** END $name ***/"
        ""
    ) | Add-Content -Path $deployPath
}

Write-Host ""
Write-Host "Done. Added migration:"
Write-Host "  $($migrations[0].Name)"
Write-Host ""
Write-Host "Deploy script created at:"
Write-Host "  $deployPath"