//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoostAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoostAnalyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await this async UoW operation.
        /// </summary>
        internal static string CodeFixTitleAwait {
            get {
                return ResourceManager.GetString("CodeFixTitleAwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use await on EF async query instead of blocking.
        /// </summary>
        internal static string CodeFixTitleBlockingEfQuery {
            get {
                return ResourceManager.GetString("CodeFixTitleBlockingEfQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await this async repository call.
        /// </summary>
        internal static string CodeFixTitleRepoAwait {
            get {
                return ResourceManager.GetString("CodeFixTitleRepoAwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async repo method and await.
        /// </summary>
        internal static string CodeFixTitleRepoSync {
            get {
                return ResourceManager.GetString("CodeFixTitleRepoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async UOW method and await.
        /// </summary>
        internal static string CodeFixTitleSyncInAsync {
            get {
                return ResourceManager.GetString("CodeFixTitleSyncInAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use async EF Core query and await.
        /// </summary>
        internal static string CodeFixTitleSyncLinqInAsync {
            get {
                return ResourceManager.GetString("CodeFixTitleSyncLinqInAsync", resourceCulture);
            }
        }
    }
}
