/*
    Database deploy script (PgSQL)
    Generated: 2026-03-10 01:12:40
    ConnName: TestPg
*/

/*** BEGIN InitDbTest.pgsql ***/

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'my') THEN
        CREATE SCHEMA my;
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE my."MyTable" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowVersion" bigint NOT NULL,
    "RowID" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Code" varchar(30) NOT NULL,
    "Heading" varchar(256),
    "Balance" numeric(19,4) NOT NULL,
    "Status" integer NOT NULL,
    "Discount" numeric(18,8) NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastChangedBy" varchar(256) NOT NULL,
    CONSTRAINT "PK_MyTable" PRIMARY KEY ("Id")
);

CREATE TABLE my."MyTableRef" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowVersion" bigint NOT NULL,
    "ParentId" bigint NOT NULL,
    "MyInfo" varchar(256) NOT NULL,
    "Amount" numeric(19,4) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "LastChangedBy" varchar(256) NOT NULL,
    CONSTRAINT "PK_MyTableRef" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MyTableRef_MyTable_ParentId" FOREIGN KEY ("ParentId") REFERENCES my."MyTable" ("Id") ON DELETE RESTRICT
);

INSERT INTO my."MyTable" ("Id", "Balance", "Code", "Created", "Discount", "Heading", "LastChanged", "LastChangedBy", "RowID", "RowVersion", "Status")
VALUES (-2, 200.0, 'Mn', TIMESTAMPTZ '2026-03-10T01:12:36.589409+00:00', 0.0, 'Mando', TIMESTAMPTZ '2026-03-10T01:12:36.589409+00:00', 'Stefan', '998cbbc6-7c86-4a55-9b27-a8282c13a6e2', 0, 2);
INSERT INTO my."MyTable" ("Id", "Balance", "Code", "Created", "Discount", "Heading", "LastChanged", "LastChangedBy", "RowID", "RowVersion", "Status")
VALUES (-1, 350.0, 'BD', TIMESTAMPTZ '2026-03-10T01:12:36.589406+00:00', 5.0, 'Baldo', TIMESTAMPTZ '2026-03-10T01:12:36.589406+00:00', 'Baldr', '5b63dc6d-42b5-4d3e-a259-62b826649579', 0, 1);

INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-3, 200.0, TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', 'Stefan', 'OtherData', -2, 0);
INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-2, 50.0, TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', 'Baldr', 'BiggerData', -1, 0);
INSERT INTO my."MyTableRef" ("Id", "Amount", "Created", "LastChanged", "LastChangedBy", "MyInfo", "ParentId", "RowVersion")
VALUES (-1, 300.0, TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', TIMESTAMPTZ '2026-03-10T01:12:36.589421+00:00', 'Baldr', 'BigData', -1, 0);

CREATE INDEX "IX_MyTable_LastChanged" ON my."MyTable" ("LastChanged");

CREATE UNIQUE INDEX "IX_MyTable_RowID" ON my."MyTable" ("RowID");

CREATE INDEX "IX_MyTableRef_MyInfo" ON my."MyTableRef" ("MyInfo");

CREATE INDEX "IX_MyTableRef_ParentId" ON my."MyTableRef" ("ParentId");

SELECT setval(
    pg_get_serial_sequence('my."MyTable"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTable") + 1,
        nextval(pg_get_serial_sequence('my."MyTable"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('my."MyTableRef"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTableRef") + 1,
        nextval(pg_get_serial_sequence('my."MyTableRef"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310011236_InitDbTest', '8.0.24');

COMMIT;


GO
/*** END InitDbTest.pgsql ***/


/*** BEGIN PgSQL.pgsql ***/

CREATE SCHEMA IF NOT EXISTS my;

CREATE SEQUENCE my."MySeq"
    AS bigint
    START WITH 1
    INCREMENT BY 1
    MINVALUE -9223372036854775808
    MAXVALUE 9223372036854775807
    CACHE 1;

CREATE OR REPLACE FUNCTION my."ReserveMyIds"(IdCount INT)
RETURNS TABLE(id BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT nextval('my."MySeq"') FROM generate_series(1, IdCount);
END;
$$ LANGUAGE plpgsql;

-- Stored procedure test scalar result
CREATE OR REPLACE FUNCTION my."GetMaxIdByChanger"(Changer VARCHAR(50)) RETURNS BIGINT AS $$
BEGIN
    RETURN (
        SELECT MAX("Id") FROM my."MyTable" WHERE "LastChangedBy" = Changer
    );
END;
$$ LANGUAGE plpgsql;

CREATE VIEW my."MyTableRefView" AS
SELECT
    r."Id" AS "RefId",
    t."Id" AS "MyId",
    r."RowVersion",
    t."RowID",
    t."Code",
    t."Heading",
    t."LastChanged" as "ParLastChanged",
    t."LastChangedBy" as "ParLastChangedBy",
    r."MyInfo",
    r."Amount",
    r."Created",
    r."LastChanged",
    r."LastChangedBy"
FROM my."MyTableRef" r
INNER JOIN my."MyTable" t ON t."Id" = r."ParentId";

CREATE OR REPLACE FUNCTION my."GetMyTableRefViewByMyId"(MyId BIGINT)
RETURNS SETOF my."MyTableRefView" AS $$
BEGIN
    RETURN QUERY
    SELECT * FROM my."MyTableRefView" WHERE "MyId" = MyId;
END;
$$ LANGUAGE plpgsql;


GO
/*** END PgSQL.pgsql ***/

