CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'my') THEN
        CREATE SCHEMA my;
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE my."MyTable" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowID" uuid NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "LastChangedBy" citext NOT NULL,
    CONSTRAINT "PK_MyTable" PRIMARY KEY ("Id")
);

CREATE TABLE my."MyTableRef" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ParentId" bigint NOT NULL,
    "MyInfo" citext NOT NULL,
    "LastChanged" timestamp with time zone NOT NULL,
    "LastChangedBy" citext NOT NULL,
    CONSTRAINT "PK_MyTableRef" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MyTableRef_MyTable_ParentId" FOREIGN KEY ("ParentId") REFERENCES my."MyTable" ("Id") ON DELETE RESTRICT
);

INSERT INTO my."MyTable" ("Id", "LastChanged", "LastChangedBy", "RowID")
VALUES (-2, TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Stefan', 'caa5a062-c9bb-494f-bf9d-538e64f20b6a');
INSERT INTO my."MyTable" ("Id", "LastChanged", "LastChangedBy", "RowID")
VALUES (-1, TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Baldr', 'ac4b0a74-e0b6-42eb-b11c-71ac0db378be');

INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-3, TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Stefan', 'OtherData', -2);
INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-2, TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Baldr', 'BiggerData', -1);
INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-1, TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Baldr', 'BigData', -1);

CREATE INDEX "IX_MyTable_LastChanged" ON my."MyTable" ("LastChanged");

CREATE UNIQUE INDEX "IX_MyTable_RowID" ON my."MyTable" ("RowID");

CREATE INDEX "IX_MyTableRef_MyInfo" ON my."MyTableRef" ("MyInfo");

CREATE INDEX "IX_MyTableRef_ParentId" ON my."MyTableRef" ("ParentId");

SELECT setval(
    pg_get_serial_sequence('my."MyTable"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTable") + 1,
        nextval(pg_get_serial_sequence('my."MyTable"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('my."MyTableRef"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTableRef") + 1,
        nextval(pg_get_serial_sequence('my."MyTableRef"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260113164323_InitDbTest', '8.0.21');

COMMIT;

