CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'my') THEN
        CREATE SCHEMA my;
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE my."MyTable" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RowID" uuid NOT NULL,
    "LastChanged" timestamp without time zone NOT NULL,
    "LastChangedBy" citext NOT NULL,
    CONSTRAINT "PK_MyTable" PRIMARY KEY ("Id")
);

CREATE TABLE my."MyTableRef" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ParentId" bigint NOT NULL,
    "MyInfo" citext NOT NULL,
    "LastChanged" timestamp without time zone NOT NULL,
    "LastChangedBy" citext NOT NULL,
    CONSTRAINT "PK_MyTableRef" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MyTableRef_MyTable_ParentId" FOREIGN KEY ("ParentId") REFERENCES my."MyTable" ("Id") ON DELETE CASCADE
);

INSERT INTO my."MyTable" ("Id", "LastChanged", "LastChangedBy", "RowID")
VALUES (-2, TIMESTAMP '1970-01-01T00:00:00', 'Stefan', 'f44937a3-23f3-4c6d-893d-01988c6aa8c8');
INSERT INTO my."MyTable" ("Id", "LastChanged", "LastChangedBy", "RowID")
VALUES (-1, TIMESTAMP '1970-01-01T00:00:00', 'Baldr', '901adebf-fbf3-409f-b4b5-0dc769993ade');

INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-3, TIMESTAMP '1970-01-01T00:00:00', 'Stefan', 'OtherData', 2);
INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-2, TIMESTAMP '1970-01-01T00:00:00', 'Baldr', 'BiggerData', 1);
INSERT INTO my."MyTableRef" ("Id", "LastChanged", "LastChangedBy", "MyInfo", "ParentId")
VALUES (-1, TIMESTAMP '1970-01-01T00:00:00', 'Baldr', 'BigData', 1);

CREATE INDEX "IX_MyTable_LastChanged" ON my."MyTable" ("LastChanged");

CREATE UNIQUE INDEX "IX_MyTable_RowID" ON my."MyTable" ("RowID");

CREATE INDEX "IX_MyTableRef_MyInfo" ON my."MyTableRef" ("MyInfo");

CREATE INDEX "IX_MyTableRef_ParentId" ON my."MyTableRef" ("ParentId");

SELECT setval(
    pg_get_serial_sequence('my."MyTable"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTable") + 1,
        nextval(pg_get_serial_sequence('my."MyTable"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('my."MyTableRef"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM my."MyTableRef") + 1,
        nextval(pg_get_serial_sequence('my."MyTableRef"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251124153837_InitDbTest', '8.0.21');

COMMIT;

